void setScreen(){
  //先重置設定，防止重新遊戲時人物亂動
  walkSpeedx=0;
  walkSpeedy=0;
  walkAccelx=0;
  walkAccelxtmp=0;
  //小人靜止
  if(level_where<7 && level_where>2){
    imageMode(CENTER);
    image(img_stop,playerx,playery+ground_corrected_value,person_width,person_height);
  }
  imageMode(CORNER);
  //設定按鈕
  image(img_btnset,btn_setx,btn_sety,set_width,set_height);
  //設定板
  image(img_setboard,board_setx,board_sety,boardset_width,boardset_height);
  image(img_del,btn_delx,btn_dely,del_width,del_height);
  image(img_home,btn_homex,btn_homey,home_width,home_height);
  if(!volume_mute){
    image(img_volumeBtnON,btn_volumex,btn_volumey,volumebtn_width,volumebtn_height);
  }
  else{
    image(img_volumeBtnOFF,btn_volumex,btn_volumey,volumebtn_width,volumebtn_height);
  }
  if(!soundeffect_mute){
    image(img_volumeBtnON,btn_soundeffectx,btn_soundeffecty,volumebtn_width,volumebtn_height);
  }
  else{
    image(img_volumeBtnOFF,btn_soundeffectx,btn_soundeffecty,volumebtn_width,volumebtn_height);
  }
  imageMode(CENTER);
  image(img_mute,mute_x,volume_liney,mute_width,mute_height);
  image(img_mute,mute_x,soundeffect_liney,mute_width,mute_height);
  image(img_maxvolume,maxvolume_x,volume_liney,maxvolume_width,maxvolume_height);
  image(img_maxvolume,maxvolume_x,soundeffect_liney,maxvolume_width,maxvolume_height);
  image(img_volumeline,volume_linex,volume_liney,volumeline_width,volumeline_height);
  image(img_volumeline,soundeffect_linex,soundeffect_liney,volumeline_width,volumeline_height);
  image(img_volumewhere,volume_wherex,volume_wherey,volumewhere_width,volumewhere_height);
  image(img_volumewhere,soundeffect_wherex,soundeffect_wherey,volumewhere_width,volumewhere_height);
}
